functionsDirectory = "/mnt/d/vscode_workspace/template-decap-cms-docusaurus/netlify/functions"
functionsDirectoryOrigin = "config-v1"
plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/mnt/d/vscode_workspace/template-decap-cms-docusaurus/build"
publishOrigin = "config"
commandOrigin = "config"
command = "yarn build"
functions = "/mnt/d/vscode_workspace/template-decap-cms-docusaurus/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]